In [1]:
import matplotlib.pyplot as plt 
%matplotlib inline

from dispersant_screener.utils import read_pickle, get_random_exploration_bl
import numpy as np 
from functools import partial
from matplotlib import animation, rc

COLORS = [
    "#ffbe0b", 
    "#fb5607", 
    "#ff006e",
    "#3a86ff", 
]

In [12]:
pareto_optimal = np.load('../work/20201005-2211070.05_0.05_0.08333333333333333_40-pareto_optimal_indices.npy', allow_pickle=True)#read_pickle('../work/20200830-112437-history.pkl')

In [14]:
pareto_optimal

array([array([20, 33]), array([20, 33]), array([  20,   33, 3103]),
       array([  20,   33, 3102, 3103, 3109, 3120, 3121, 3122, 3124]),
       array([  20,   33, 3102, 3103, 3109, 3120, 3121, 3122, 3124]),
       array([  20,   33, 3102, 3103, 3109, 3120, 3121, 3122, 3124]),
       array([  20,   33, 3102, 3103, 3109, 3120, 3121, 3122, 3124]),
       array([  20,   33, 3102, 3103, 3109, 3120, 3121, 3122, 3124]),
       array([  20,   33, 3102, 3103, 3109, 3120, 3121, 3122, 3124]),
       array([  20,   33, 3102, 3103, 3109, 3120, 3121, 3122, 3124]),
       array([  20,   33,   43, 3102, 3103, 3106, 3107, 3109, 3120, 3121, 3122,
       3123, 3124]),
       array([  20,   33,   43, 3102, 3103, 3106, 3107, 3109, 3120, 3121, 3122,
       3123, 3124]),
       array([  20,   33,   43, 3102, 3103, 3106, 3107, 3109, 3120, 3121, 3122,
       3123, 3124]),
       array([  20,   33,   43, 3102, 3103, 3105, 3106, 3107, 3109, 3120, 3121,
       3122, 3123, 3124]),
       array([  20,   33,   43, 